# Generated by Django 4.2.30 on 2026-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trip",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RIDER", "Rider"),
                    ("DRIVER", "Driver"),
                    ("SYSTEM", "System"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="otp",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="trip",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("ACCEPTED", "Accepted"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="REQUESTED",
                max_length=20,
            ),
        ),
    ]
