# Generated by Django 6.0.6 on 2026-06-30 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_rides', models.IntegerField(default=0)),
                ('wallet_balance', models.BigIntegerField(default=0)),
                ('home_address', models.CharField(blank=True, max_length=500, null=True)),
                ('work_address', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_profiles',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('card', 'card'), ('upi', 'upi'), ('wallet', 'wallet')], max_length=10)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=7, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=150, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_name', models.CharField(blank=True, max_length=150, null=True)),
                ('razorpay_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='customers.riderprofile')),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='customers.riderprofile')),
            ],
            options={
                'db_table': 'emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('home', 'home'), ('work', 'work'), ('other', 'other')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to='customers.riderprofile')),
            ],
            options={
                'db_table': 'saved_places',
            },
        ),
    ]
