# Generated by Django 5.2.8 on 2026-07-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedplace',
            constraint=models.UniqueConstraint(fields=('rider', 'label'), name='unique_saved_place_per_rider_label'),
        ),
    ]
