# Generated by Django 5.2.8 on 2026-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_savedplace_unique_saved_place_per_rider_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedplace',
            name='label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], max_length=20),
        ),
    ]
