# Generated by Django 6.0.6 on 2026-07-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_wallettransaction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedplace',
            name='unique_saved_place_per_rider_label',
        ),
        migrations.AlterField(
            model_name='savedplace',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='savedplace',
            constraint=models.UniqueConstraint(condition=models.Q(('label__in', ['home', 'work'])), fields=('rider', 'label'), name='unique_home_work_saved_place_per_rider'),
        ),
    ]
