# Generated by Django 5.2.15 on 2026-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_type', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('car', 'Car')], max_length=10, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('per_km_fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
