"""
Django settings for nqtaxi project.

Generated by 'django-admin startproject' using Django 6.0.6.
Configured for NQTaxi Backend with DRF, CORS, and python-decouple.
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me-in-production')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# =============================================================================
# APPLICATIONS
# =============================================================================

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
]

LOCAL_APPS = [
    'accounts',           # custom User model (accounts.User)
    'apps.core',
    'apps.users',
    'apps.customers',
    'apps.rides',
    'apps.trips',
    'apps.drivers',
    'apps.payments',
    'apps.ratings',
    'apps.notifications',
    'apps.fares',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',          # CORS — must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apps.nqtaxi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.nqtaxi.wsgi.application'


# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
    }
}


# =============================================================================
# MEDIA FILES  (uploaded documents, profile photos, etc.)
# =============================================================================

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# AUTHENTICATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# DJANGO REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',   # kept for admin
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'apps.core.exceptions.custom_exception_handler',
}


# =============================================================================
# SPECTACULAR SETTINGS
# =============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'NQTaxi API',
    'DESCRIPTION': (
        'REST API documentation for the NQTaxi Backend.\n\n'
        '## Authentication\n'
        'All driver endpoints require a **Bearer JWT token**. '
        'Obtain a token via `POST /api/v1/auth/token/` and click the '
        '**Authorize** button to set it in Swagger UI.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Show the Authorize button and define the JWT Bearer security scheme
    'SECURITY': [{'BearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'BearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'Enter your JWT access token. Example: `Bearer <your_token>`',
        }
    },

    # Sort endpoints and schemas alphabetically for easier navigation
    'SORT_OPERATIONS': False,
    'SORT_OPERATION_PARAMETERS': True,
    'COMPONENT_SPLIT_REQUEST': True,

    # Tag ordering for Swagger sidebar
    'TAGS': [
        {'name': 'Auth',                    'description': 'JWT token endpoints'},
        {'name': 'Driver – Profile',        'description': 'Driver profile management'},
        {'name': 'Driver – Vehicle',        'description': 'Vehicle registration and management'},
        {'name': 'Driver – Documents',      'description': 'KYC document upload and management'},
        {'name': 'Driver – Status',         'description': 'Driver online/offline status toggle'},
        {'name': 'Driver – Wallet',         'description': 'Wallet balance and withdrawal requests'},
        {'name': 'Driver – Bank Details',   'description': 'Payout bank account management'},
        {'name': 'Driver – Earnings & Stats', 'description': 'Earnings breakdown and driver statistics'},
        {'name': 'Driver – Trip History',   'description': 'Paginated trip history'},
        {'name': 'Driver – Incentives',     'description': 'Active incentives and progress tracking'},
        {'name': 'Driver – Location',       'description': 'Real-time GPS location updates'},
        {'name': 'Trips',                   'description': 'Ride lifecycle: request, accept, start, complete, cancel'},
    ],
}


# =============================================================================
# SIMPLE JWT
# =============================================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(
        minutes=config('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', default=60, cast=int)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=7, cast=int)
    ),
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}


# =============================================================================
# CORS
# =============================================================================

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:5173',
    cast=Csv(),
)

CORS_ALLOW_CREDENTIALS = True


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================

STATIC_URL = config('STATIC_URL', default='/static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = config('MEDIA_URL', default='/media/')
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# CUSTOM USER MODEL
# =============================================================================

# The entire project (drivers, customers, trips, etc.) is built on accounts.User
# which adds phone, role, and OTP fields on top of AbstractUser.
AUTH_USER_MODEL = 'accounts.User'


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# RAZORPAY
# =============================================================================

RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')
RAZORPAY_AUTO_COMPLETE_TOPUP = config('RAZORPAY_AUTO_COMPLETE_TOPUP', default=False, cast=bool)

